// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD48tJ0hAleH7rBkB8QsiAtMxUieqIY3HE',
    appId: '1:392237132140:web:1cb5a20364c5026827ab49',
    messagingSenderId: '392237132140',
    projectId: 'fire-app-9cb26',
    authDomain: 'fire-app-9cb26.firebaseapp.com',
    storageBucket: 'fire-app-9cb26.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVdbSyiH6nCUuEDZxRwiY4zabfnJIwWwc',
    appId: '1:392237132140:android:685727af2774ed3127ab49',
    messagingSenderId: '392237132140',
    projectId: 'fire-app-9cb26',
    storageBucket: 'fire-app-9cb26.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAai0tE_BIlLc2pLs4z8dS11KutC7Wjutg',
    appId: '1:392237132140:ios:8b7eb0806776e93b27ab49',
    messagingSenderId: '392237132140',
    projectId: 'fire-app-9cb26',
    storageBucket: 'fire-app-9cb26.appspot.com',
    iosBundleId: 'com.example.fireApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAai0tE_BIlLc2pLs4z8dS11KutC7Wjutg',
    appId: '1:392237132140:ios:8b7eb0806776e93b27ab49',
    messagingSenderId: '392237132140',
    projectId: 'fire-app-9cb26',
    storageBucket: 'fire-app-9cb26.appspot.com',
    iosBundleId: 'com.example.fireApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD48tJ0hAleH7rBkB8QsiAtMxUieqIY3HE',
    appId: '1:392237132140:web:afd70bd2452db8c827ab49',
    messagingSenderId: '392237132140',
    projectId: 'fire-app-9cb26',
    authDomain: 'fire-app-9cb26.firebaseapp.com',
    storageBucket: 'fire-app-9cb26.appspot.com',
  );
}
